# Задание по теме «LU- и LDU-разложение матриц»

1. Найти LU- и LDU-разложение матрицы. Проверить, что А=LU=LDU. Выписать матрицы преобразований Е, произведение которых дают матрицу U, а также их обратные, произведения которых дают матрицу L. Описать, что сделает с исходной матрицей ее умножение на каждую из матриц Е слева.

Вариант 2. Задаю матрицу А.

In [1]:
import numpy as np

A = np.array([[2, -3, 0],
            [4, -5, 1],
            [2, 0, 1]])

Создаю функцию для нахождения LU разложения

In [2]:
def find_lu(a):
    u = np.zeros_like(a)
    l = np.eye(a.shape[0])
    
    for i in range(a.shape[0]):
        for j in range(a.shape[0]):
            if i <= j:
                sum = 0
                for k in range(i):
                    sum += l[i][k] * u[k][j]
                u[i][j] = a[i][j] - sum
            if i > j:
                sum = 0
                for k in range(i):
                    sum += l[i][k] * u[k][j]
                l[i][j] = (a[i][j] - sum)/u[j][j]
    return l, u

Нахожу матрицу L и U. Проверяю, что A = LU

In [3]:
L, U = find_lu(A)
print('L:')
print(L)
print('U:')
print(U)
print('A:')
print(A)
print('LU:')
print(L@U)

L:
[[1. 0. 0.]
 [2. 1. 0.]
 [1. 3. 1.]]
U:
[[ 2 -3  0]
 [ 0  1  1]
 [ 0  0 -2]]
A:
[[ 2 -3  0]
 [ 4 -5  1]
 [ 2  0  1]]
LU:
[[ 2. -3.  0.]
 [ 4. -5.  1.]
 [ 2.  0.  1.]]


Выписал матрицы преобразований Е, произведение которых дают матрицу U

Вычитание удвоенного первого уравнения из второго:

In [4]:
print('U:')
print(U)
e1 = np.array([[1, 0, 0],
               [-2, 1, 0],
               [0, 0, 1]])
print('E1:')
print(e1)
e1a = np.array([[2, -3, 0],
               [0, 1, 1],
               [2, 0, 1]])
print('E1 * A:')
print(e1a)

U:
[[ 2 -3  0]
 [ 0  1  1]
 [ 0  0 -2]]
E1:
[[ 1  0  0]
 [-2  1  0]
 [ 0  0  1]]
E1 * A:
[[ 2 -3  0]
 [ 0  1  1]
 [ 2  0  1]]


Вычитание первого уравнения, из третьего:

In [5]:
print('U:')
print(U)
e2 = np.array([[1, 0, 0],
               [0, 1, 0],
               [-1, 0, 1]])
print('E2:')
print(e2)
e2e1a = np.array([[2, -3, 0],
               [0, 1, 1],
               [0, 3, 1]])
print('E2 * E1 * A:')
print(e2e1a)

U:
[[ 2 -3  0]
 [ 0  1  1]
 [ 0  0 -2]]
E2:
[[ 1  0  0]
 [ 0  1  0]
 [-1  0  1]]
E2 * E1 * A:
[[ 2 -3  0]
 [ 0  1  1]
 [ 0  3  1]]


Вычитание второго уравнения умноженного на 3, из третьего:

In [6]:
print('U:')
print(U)
e3 = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, -3, 1]])
print('E3')
print(e3)
e3e2e1a = np.array([[2, -3, 0],
               [0, 1, 1],
               [0, 0, -2]])
print('E3 * E2 * E1 * A:')
print(e3e2e1a)

U:
[[ 2 -3  0]
 [ 0  1  1]
 [ 0  0 -2]]
E3
[[ 1  0  0]
 [ 0  1  0]
 [ 0 -3  1]]
E3 * E2 * E1 * A:
[[ 2 -3  0]
 [ 0  1  1]
 [ 0  0 -2]]


Проверяю, что произведение обратных матриц E дает матрицу L.

In [7]:
e1_inv = np.linalg.inv(e1)
e2_inv = np.linalg.inv(e2)
e3_inv = np.linalg.inv(e3)
l_check = e1_inv @ e2_inv @ e3_inv
print('L:')
print(L)
print('E3_inv * E2_inv * E1_inv:')
print(l_check)

L:
[[1. 0. 0.]
 [2. 1. 0.]
 [1. 3. 1.]]
E3_inv * E2_inv * E1_inv:
[[1. 0. 0.]
 [2. 1. 0.]
 [1. 3. 1.]]


Создаю функцию для нахождения матриц L, D, U.

In [8]:
def find_ldu(a):
    l = np.eye(a.shape[0])
    d = np.eye(a.shape[0])
    u = np.eye(a.shape[0])
    
    for i in range(a.shape[0]):
        for j in range(a.shape[0]):               
            if i <= j:           
                sum = 0
                for k in range(i):
                    sum += l[i][k] * u[k][j]
                if i==j:
                    d[i][j] = a[i][j] - sum
                u[i][j] = a[i][j] - sum
            if i > j:
                sum = 0
                for k in range(i):
                    sum += l[i][k] * u[k][j]
                l[i][j] = (a[i][j] - sum)/u[j][j]
    for i in range(u.shape[0]):
        for j in range(u.shape[0]):
            if i==j:
                u[i][j] = 1
            else:
                if i <= j:           
                    u[i][j] = u[i][j] / d[i][i]
    return l, d, u

Нахожу L, D, U. Проверяю, что А=LDU.

In [9]:
l, d, u = find_ldu(A)
print('L:')
print(l)
print('D:')
print(d)
print('U:')
print(u)
print('A:')
print(A)
print('LDU:')
print(l@d@u)

L:
[[1. 0. 0.]
 [2. 1. 0.]
 [1. 3. 1.]]
D:
[[ 2.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -2.]]
U:
[[ 1.  -1.5  0. ]
 [ 0.   1.   1. ]
 [ 0.   0.   1. ]]
A:
[[ 2 -3  0]
 [ 4 -5  1]
 [ 2  0  1]]
LDU:
[[ 2. -3.  0.]
 [ 4. -5.  1.]
 [ 2.  0.  1.]]


2. Придумать вектор b, и решить систему Ax=b с помощью LU- или LDU- разложения матрицы А. Проверьте правильность решения. 

Задаю вектор b.

In [10]:
b = np.array([3, 10, 5])

Нахожу с = L<sup>-1</sup>b

In [11]:
c = np.linalg.inv(L) @ b
print('c:')
print(c)

c:
[  3.   4. -10.]


Нахожу x = U<sup>-1</sup>c

In [12]:
x = np.linalg.inv(U) @ c
print('x:')
print(x)

x:
[ 0. -1.  5.]


Проверяю, что Ax = b

In [13]:
print('b:')
print(b)
print('Ax:')
print(A @ x)

b:
[ 3 10  5]
Ax:
[ 3. 10.  5.]


3. Найти разложение на нижнюю треугольную и верхнюю унитреугольную матрицу по формулам X=Y\*Z. Здесь Х=А. Проверить, что Х=Y*Z. Сделать LDU- разложения матрицы А=Х и убедиться, что хотя разложения на нижнюю и верхнюю треугольные матрицы не обязательно совпадает, LDU- разложение будет одно.

Создал функцию для нахождения Y и Z

In [14]:
def find_yz(x):
    y = np.zeros_like(x)
    z = np.eye(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if j == 0:
                y[i][j] = x[i][j]
            if i == 0:
                z[i][j] = x[i][j] / y[i][i]    
            if (i >= j and j >= 1):
                sum = 0
                for k in range(i):
                    sum += y[i][k] * z[k][j]
                y[i][j] = x[i][j] - sum
            if (0 < i and i < j):
                sum = 0
                for k in range(i):
                    sum += y[i][k] * z[k][j]
                z[i][j] = (x[i][j] - sum) / y[i][i]
    return y,z                

Нашел Y и Z. Проверил, что X=Y*Z

In [15]:
Y, Z = find_yz(A)
print('Y:')
print(Y)
print('Z:')
print(Z)
print('X:')
print(A)
print('Y*Z:')
print(Y@Z)

Y:
[[ 2  0  0]
 [ 4  1  0]
 [ 2  3 -2]]
Z:
[[ 1.  -1.5  0. ]
 [ 0.   1.   1. ]
 [ 0.   0.   1. ]]
X:
[[ 2 -3  0]
 [ 4 -5  1]
 [ 2  0  1]]
Y*Z:
[[ 2. -3.  0.]
 [ 4. -5.  1.]
 [ 2.  0.  1.]]


Сравнил с LDU Разложением. Матрица Y не обязательно совпадает с матрицей L.

In [16]:
print('L:')
print(l)
print('D:')
print(d)
print('U:')
print(u)

L:
[[1. 0. 0.]
 [2. 1. 0.]
 [1. 3. 1.]]
D:
[[ 2.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -2.]]
U:
[[ 1.  -1.5  0. ]
 [ 0.   1.   1. ]
 [ 0.   0.   1. ]]


4. Написать, где может использоваться LU- и LDU-разложение матриц.

LU- и LDU-разложение матриц могут использоваться в разных областях, где часто возникает необходимость решения большого числа линейных уравнений, например:
- алгоритмы машинного обучения;
- работа с изображениями и графикой;
- моделирования и симуляции.
- инженерные расчеты.