# Задание по теме «QR-разложение»

1. Варианты заданий возьмите в Задании по теме «Решение систем линейных алгебраических уравнений»
Для Вашей матрицы постройте QR-разложение методом вращений Гивенса ИЛИ методом отражений Хаусхолдера (можно даже по алгоритму Грамма-Шмидта). Проверьте, что A=QR, Q – ортогональная матрица и определитель Q равен 1. Найдите определитель матрицы А, используя данное разложение. Найдите решение системы Ax=b, используя данное разложение. 

Вариант 2. Задаю матрицу А и вектор b.

In [26]:
import numpy as np

A = np.array([[-3, 0.5, 0.5],
              [0.5, -6, 0.5],
              [0.5, 0.5, -3]])
b = np.array([-56.5, 100, -210])

Создал функцию для нахождения матрицы Q и R по алгоритму Грамма-Шмидта.

In [54]:
def find_qr(A):
    n, m = A.shape
    Q = np.empty((n, n))
    u = np.empty((n, n))

    u[:, 0] = A[:, 0]
    Q[:, 0] = u[:, 0] / np.linalg.norm(u[:, 0])

    for i in range(1, n):
        u[:, i] = A[:, i]
        for j in range(i):
            u[:, i] -= (A[:, i] @ Q[:, j]) * Q[:, j]
        Q[:, i] = u[:, i] / np.linalg.norm(u[:, i])
        
    R = np.zeros((n, m))
    for i in range(n):
        for j in range(i, m):
            R[i, j] = A[:, j] @ Q[:, i]
    D = np.diag(np.sign(np.diag(Q)))
    return Q @ D, D @ R

Нахожу матрицы Q и R. Проверяю что A=QR.

In [44]:
print(q)
print(r)

[[-0.97332853 -0.14316491  0.17926346]
 [ 0.16222142 -0.98202182  0.09652648]
 [ 0.16222142  0.12303235  0.97905426]]
[[ 3.082207   -1.37888208 -0.89221782]
 [ 0.          5.88206462 -0.9316904 ]
 [ 0.          0.         -2.79926783]]


In [55]:
Q,R = find_qr(A)
print('Q:')
print(Q)
print('R:')
print(R)
print('QR:')
print(Q @ R)
print('A:')
print(A)

Q:
[[ 0.97332853  0.14316491  0.17926346]
 [-0.16222142  0.98202182  0.09652648]
 [-0.16222142 -0.12303235  0.97905426]]
R:
[[-3.082207    1.37888208  0.89221782]
 [ 0.         -5.88206462  0.9316904 ]
 [ 0.          0.         -2.79926783]]
QR:
[[-3.   0.5  0.5]
 [ 0.5 -6.   0.5]
 [ 0.5  0.5 -3. ]]
A:
[[-3.   0.5  0.5]
 [ 0.5 -6.   0.5]
 [ 0.5  0.5 -3. ]]


Проверяю, что Q - ортогональная матрица. Ее определитель равен и ее произведение на транспонированную дает единичную матрицу.

In [57]:
print('Q^-1 * Q:')
print(Q.transpose() @ Q)
print('Определитель матрицы Q:', np.linalg.det(Q))

Q^-1 * Q:
[[ 1.00000000e+00 -9.37110595e-18  4.06061511e-17]
 [-9.37110595e-18  1.00000000e+00  4.67689379e-17]
 [ 4.06061511e-17  4.67689379e-17  1.00000000e+00]]
Определитель матрицы Q: 1.0


Нахожу определитель матрицы A  по свойству: det(A) = det(Q) * det(R). Проверяю найденный определитель с результатом готовой функции для нахождения определителя.

In [58]:
print('det(A) = det(Q) * det(R) =', np.linalg.det(Q) * np.linalg.det(R))
print('Определитель матрицы A:', np.linalg.det(A))

det(A) = det(Q) * det(R) = -50.75000000000003
Определитель матрицы A: -50.74999999999998


In [ ]:
D = np.empty((n, n))
E = np.empty((n, n))
def tred2(A, n, D, E):
    for i range()