# Задание по теме «QR-разложение»

## Задание 1

1\. Варианты заданий возьмите в Задании по теме «Решение систем линейных алгебраических уравнений»
Для Вашей матрицы постройте QR-разложение методом вращений Гивенса ИЛИ методом отражений Хаусхолдера (можно даже по алгоритму Грамма-Шмидта). Проверьте, что A=QR, Q – ортогональная матрица и определитель Q равен 1. Найдите определитель матрицы А, используя данное разложение. Найдите решение системы Ax=b, используя данное разложение. 

Вариант 2. Задаю матрицу А и вектор b.

In [1]:
import numpy as np

A = np.array([[-3, 0.5, 0.5],
              [0.5, -6, 0.5],
              [0.5, 0.5, -3]])
B = np.array([-56.5, 100, -210])

Создал функцию для нахождения матрицы Q и R по алгоритму Грамма-Шмидта
$$u_1 = a_1,$$
$$u_k = a_k - \sum_{j=1}^{k-1} \text{proj}_{u_j}(a_k),$$
$$\text{proj}_{u_j}(a_k) = \frac{\langle a_k, u_j \rangle}{\langle u_j, u_j \rangle} u_j,$$
$$q_k = \frac{u_k}{\|u_k\|},$$
$$Q = [q_1 \ q_2 \ \ldots \ q_n],$$
$$R = Q^\top A$$

In [2]:
def find_qr(A):
    n, m = A.shape
    Q = np.empty((n, n))
    u = np.empty((n, n))

    u[:, 0] = A[:, 0]
    Q[:, 0] = u[:, 0] / np.linalg.norm(u[:, 0])

    for i in range(1, n):
        u[:, i] = A[:, i]
        for j in range(i):
            u[:, i] -= (A[:, i] @ Q[:, j]) * Q[:, j]
        Q[:, i] = u[:, i] / np.linalg.norm(u[:, i])
        
    R = np.zeros((n, m))
    for i in range(n):
        for j in range(i, m):
            R[i, j] = A[:, j] @ Q[:, i]
    return Q, R

Нахожу матрицы Q и R. Проверяю что A=QR.

In [3]:
Q,R = find_qr(A.copy())
print('Q:')
print(Q)
print('R:')
print(R)
print('QR:')
print(Q @ R)
print('A:')
print(A)

Q:
[[-0.97332853 -0.14316491 -0.17926346]
 [ 0.16222142 -0.98202182 -0.09652648]
 [ 0.16222142  0.12303235 -0.97905426]]
R:
[[ 3.082207   -1.37888208 -0.89221782]
 [ 0.          5.88206462 -0.9316904 ]
 [ 0.          0.          2.79926783]]
QR:
[[-3.   0.5  0.5]
 [ 0.5 -6.   0.5]
 [ 0.5  0.5 -3. ]]
A:
[[-3.   0.5  0.5]
 [ 0.5 -6.   0.5]
 [ 0.5  0.5 -3. ]]


Проверяю, что Q - ортогональная матрица.
$$Q^TQ=I,$$
$$|det(Q)=1|.$$

In [8]:
print('Q^T*Q:')
print(Q.transpose() @ Q)
print('Модуль определителя матрицы Q:', np.abs(np.linalg.det(Q)))

Q^T*Q:
[[ 1.00000000e+00 -9.37110595e-18  4.06061511e-17]
 [-9.37110595e-18  1.00000000e+00  4.67689379e-17]
 [ 4.06061511e-17  4.67689379e-17  1.00000000e+00]]
Модуль определителя матрицы Q: 1.0


Нахожу определитель матрицы A  по свойству: det(A) = det(Q) * det(R). Так как матрица R верхнаяя треугольная, можно найти определитель через произведение элементов ее главной диагонали.


Проверяю найденный определитель с результатом готовой функции для нахождения определителя.

In [10]:
print('det(A) = det(Q) * det(R) =', np.linalg.det(Q) * (R[0][0] * R[1][1] * R[2][2]))
print('Определитель матрицы A:', np.linalg.det(A))

det(A) = det(Q) * det(R) = -50.75000000000001
Определитель матрицы A: -50.74999999999998


Определил функцию для решения системы Ax=b, используя данное разложение:
$$y=Q^TB$$
$$Rx=y$$

In [11]:
def find_x(A, B, Q, R):
    y = Q.transpose() @ B
    x = np.zeros(R.shape[0])
    for i in range(x.shape[0]-1, -1, -1):
        x[i] = (y[i] - (R[i, i+1:] @ x[i+1:])) / R[i, i]
    return x

Проверяю полученное решение с решением встроенной фукнции.

In [13]:
print('x: ', find_x(A, B, Q, R))
print('Решение встроенной функции:', np.linalg.solve(A, B))

x:  [29.76108374 -8.05172414 73.6182266 ]
Решение встроенной функции: [29.76108374 -8.05172414 73.6182266 ]


## Задание 2

2\. Варианты заданий возьмите в Задании по теме «Решение систем с симметрической матрицей методом Холецкого». Приведите симметрическую матрицу А к трехдиагональному виду методом вращений Гивенса ИЛИ методом отражений Хаусхолдера. Напишите, для чего применяется сведение матриц к трехдиагональной форме.

Вариант 2. Задаю матрицу А

In [14]:
A = np.array([
    [3.14, -2.12, 1.17],
    [-2.12, 1.32, -2.45],
    [1.17, -2.45, 1.18]
])

Нахожу матрицу вращений, где:
$$t_{ii}=t_{jj}=c;\ t_{ij}=s,\ t_{ji}=-s,$$
$$c=\frac{a_{i-1,i}}{\sqrt{a^2_{i-1,i} + a^2_{i-1,j}}},$$
$$s=-\frac{a_{i-1,j}}{\sqrt{a^2_{i-1,i} + a^2_{i-1,j}}},$$
Затем применяю матрицу вращений по формуле:
$$A_k = T^T_{ij}*A_{k-1}*T_{ij}$$
где: $$i = 1,2..n-1;\ j = i+1, i+2,...n;\ k=1,2,..N; $$
$$A_0=A;\ T_{ij} - матрица\ вращения.$$
n - размерность матрицы, N - количество шагов (элементов, которые нужно занулить).

In [15]:
n = A.shape[0]
A_copy = A.copy()

def find_tridiagonal(A, n):
    for i in range(1, n - 1):
        for j in range(i + 1, n):
            T = np.eye(n)
            c = A[i-1][i] / np.sqrt(A[i-1][i]**2 + A[i-1][j]**2)
            s = -A[i-1][j] / np.sqrt(A[i-1][i]**2 + A[i-1][j]**2)
            T[i][i] = T[j][j] = c
            T[i][j] = s
            T[j][i] = -s
            A = T.transpose() @ A @ T
    return(A)

print('Оригинальная матрица:\n', A)
print('Трехдиагональная матрица:\n', find_tridiagonal(A_copy, n))

Оригинальная матрица:
 [[ 3.14 -2.12  1.17]
 [-2.12  1.32 -2.45]
 [ 1.17 -2.45  1.18]]
Трехдиагональная матрица:
 [[ 3.14000000e+00  2.42142520e+00 -8.43401833e-17]
 [ 2.42142520e+00  3.36020159e+00 -1.24677554e+00]
 [-8.43401833e-17 -1.24677554e+00 -8.60201593e-01]]


Применяю функцию на матрицу большей размерности:

In [16]:
A_big = np.array([
    [-2, -3, 1, 1],
    [-3, 1, 2, 0],
    [1, 2, -1, -3],
    [1, 0 ,-3, -2]
], dtype='float32')
A_big_copy = A_big.copy()
n_big = A_big_copy.shape[0]
print('Оригинальная матрица:\n', A_big)
print('Трехдиагональная матрица:\n', find_tridiagonal(A_big_copy, n_big))             

Оригинальная матрица:
 [[-2. -3.  1.  1.]
 [-3.  1.  2.  0.]
 [ 1.  2. -1. -3.]
 [ 1.  0. -3. -2.]]
Трехдиагональная матрица:
 [[-2.00000000e+00  3.31662468e+00  2.74945961e-08  1.14989394e-08]
 [ 3.31662468e+00 -1.09090912e+00  3.20381988e+00 -2.32262974e-17]
 [ 2.74945961e-08  3.20381988e+00 -1.31408286e+00  2.04818929e+00]
 [ 1.14989394e-08 -2.32262974e-17  2.04818929e+00  4.04991981e-01]]


Сведение матриц к трехдиагональной форме применяется для:
- Вычисления собственных значений и векторов;
- Решения систем линейных уравнений;
- Спектрального анализа матриц.

Оно значительно ускоряет вычисления за счет упрощения структуры матрицы. Также трехдиагональная форма обеспечивает высокую эффективность и устойчивость расчетов.